default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: papershift-base-app_development
  username: postgres
  password: 1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: papershift-base-app_test
  username: postgres
  password: 1234
  host: localhost
  port: 5432

production:
  <<: *default
  database: papershift-base-app_production
  username: papershift-base-app
  password: <%= ENV['papershift-base-app_DATABASE_PASSWORD'] %>
