default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: papershift-base-app_development

test:
  <<: *default
  database: papershift-base-app_test

production:
  <<: *default
  database: papershift-base-app_production
  username: papershift-base-app
  password: <%= ENV['papershift-base-app_DATABASE_PASSWORD'] %>
